name: Build Ozone Docker Image
run-name: 'Build Ozone: ${{ github.event.head_commit.message || github.ref_name }}'

on:
  push:
    branches: [ main ]
    paths:
      - 'images/ozone/**'
      - '.github/workflows/build-ozone.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'images/ozone/**'
      - '.github/workflows/build-ozone.yml'
  workflow_dispatch:
    inputs:
      ozone_ref:
        description: 'Ozone repository ref (branch/tag/commit)'
        required: false
        default: 'ozone-2.0.0'
        type: string

env:
  OZONE_VERSION: '2.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Dockerfile repository
        uses: actions/checkout@v4

      - name: Checkout Apache Ozone repository
        uses: actions/checkout@v4
        with:
          repository: apache/ozone
          ref: ${{ github.event.inputs.ozone_ref || 'ozone-2.0.0' }}
          path: ozone-src

      - name: Install protoc compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-ozone-${{ github.event.inputs.ozone_ref || 'ozone-2.0.0' }}-${{ hashFiles('ozone-src/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-ozone-${{ github.event.inputs.ozone_ref || 'ozone-2.0.0' }}-

      - name: Build Ozone from source
        working-directory: ozone-src
        run: |
          mvn clean install -DskipTests -Pdist -Dtar -DskipShade -T 1C -B \
            -Dmaven.javadoc.skip=true \
            -Dcheckstyle.skip=true \
            -Dfindbugs.skip=true \
            -Dspotbugs.skip=true \
            -Denforcer.skip=true

      - name: Move tarball to Docker build context
        run: find ozone-src/hadoop-ozone/dist/target -name "ozone-*.tar.gz" -exec mv {} images/ozone/ \;

      - name: Clean up to free disk space
        run: |
          echo "Before cleanup:"
          df -h
          rm -rf ozone-src
          rm -rf ~/.m2/repository
          docker system prune -af
          echo "After cleanup:"
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: terrestrials
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date -u +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Extract metadata for Ozone
        id: meta-ozone
        uses: docker/metadata-action@v5
        with:
          images: terrestrials/ozone
          tags: |
            type=raw,value=${{ env.OZONE_VERSION }}-${{ steps.timestamp.outputs.timestamp }},enable={{is_default_branch}}
            type=raw,value=${{ env.OZONE_VERSION }},enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Ozone image
        uses: docker/build-push-action@v5
        with:
          context: images/ozone
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-ozone.outputs.tags }}
          labels: ${{ steps.meta-ozone.outputs.labels }}
          build-args: |
            OZONE_TARBALL=ozone-*.tar.gz
          platforms: linux/amd64,linux/arm64

      - name: Send notification to Telegram
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            STATUS_ICON="✅"
            STATUS_TEXT="Success"
          else
            STATUS_ICON="❌"
            STATUS_TEXT="Failure"
          fi
          COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c1-7)
          REPO_NAME=$(echo "${{ github.repository }}" | sed 's/[._-]/\\&/g')
          WORKFLOW_NAME=$(echo "${{ github.workflow }}" | sed 's/[._-]/\\&/g')
          COMMIT_MESSAGE=$(echo "${{ github.event.head_commit.message }}" | sed 's/[._-]/\\&/g' | tr -d '\n\r')
          MESSAGE="*${STATUS_ICON} ${WORKFLOW_NAME}: ${STATUS_TEXT}*
          
          *Repository*: \`${REPO_NAME}\`
          *Commit*: \`${COMMIT_HASH}\` \- _${COMMIT_MESSAGE}_
          
          [View Workflow Run on GitHub](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=${MESSAGE}" \
          -d "parse_mode=MarkdownV2"