name: Build Base Docker Image
run-name: 'Build Base Image: ${{ github.event.head_commit.message || github.ref_name }}'

on:
  push:
    branches: [ main ]
    paths:
      - 'images/base/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/reusable-docker-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'images/base/**'
      - '.github/workflows/build-base.yml'
      - '.github/workflows/reusable-docker-build.yml'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      image_version: 'latest' # Define the version/tag for the base image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload build context artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-context
          path: images/base

  build:
    needs: prepare
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-docker-build.yml@main
    with:
      workflow_name: 'Build Base Docker Image'
      image_name: 'terrestrials/base'
      image_context: 'images/base'
      image_version: ${{ needs.prepare.outputs.image_version }}
    secrets: inherit