name: Build Hive Docker Image
run-name: 'Build Hive: ${{ github.event.head_commit.message || github.ref_name }}'

on:
  push:
    branches: [ main ]
    paths:
      - 'images/hive/**'
      - '.github/workflows/build-hive.yml'
      - '.github/workflows/reusable-docker-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'images/hive/**'
      - '.github/workflows/build-hive.yml'
      - '.github/workflows/reusable-docker-build.yml'
  workflow_dispatch:
    inputs:
      hive_version:
        description: 'Hiveのバージョン'
        required: false
        default: '3.1.3'
        type: string
      tez_version:
        description: 'Tezのバージョン'
        required: false
        default: '0.9.2'
        type: string

env:
  HIVE_VERSION: ${{ github.event.inputs.hive_version || '3.1.3' }}
  TEZ_VERSION: ${{ github.event.inputs.tez_version || '0.9.2' }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      hive_version: ${{ env.HIVE_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build context directory
        run: mkdir -p images/hive

      - name: Download pre-built Hive binary
        run: |
          echo "Downloading Hive version ${{ env.HIVE_VERSION }}..."
          curl -fsSL "https://archive.apache.org/dist/hive/hive-${{ env.HIVE_VERSION }}/apache-hive-${{ env.HIVE_VERSION }}-bin.tar.gz" -o images/hive/hive-release.tar.gz
          echo "Download complete."

      - name: Download pre-built Tez binary
        run: |
          echo "Downloading Tez version ${{ env.TEZ_VERSION }}..."
          curl -fsSL "https://archive.apache.org/dist/tez/${{ env.TEZ_VERSION }}/apache-tez-${{ env.TEZ_VERSION }}-bin.tar.gz" -o images/hive/tez-release.tar.gz
          echo "Download complete."

      - name: Upload build context artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-context
          path: images/hive

  build:
    needs: prepare
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      workflow_name: 'Build Hive Docker Image'
      image_name: 'terrestrials/hive'
      image_context: 'images/hive'
      image_version: ${{ needs.prepare.outputs.hive_version }}
      build_args: |
        HIVE_TARBALL=hive-release.tar.gz
        TEZ_TARBALL=tez-release.tar.gz
    secrets: inherit