name: Build Base Docker Image
run-name: 'Build Base Image: ${{ github.event.head_commit.message || github.ref_name }}'

on:
  push:
    branches: [ main ]
    paths:
      - 'images/base/**'
      - '.github/workflows/build-base.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'images/base/**'
      - '.github/workflows/build-base.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Dockerfile repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: terrestrials
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Base Image
        id: meta-base
        uses: docker/metadata-action@v5
        with:
          images: terrestrials/base
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Base image
        uses: docker/build-push-action@v5
        with:
          context: images/base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          # Enable cache to speed up subsequent builds
          cache-from: type=registry,ref=terrestrials/base:latest
          cache-to: type=inline

      - name: Send notification to Telegram
        if: always()
        # NOTE: Copy the notification step from your existing workflows
        run: |
          if [ ${{ job.status }} == 'success' ]; then STATUS_ICON="✅"; STATUS_TEXT="Success"; else STATUS_ICON="❌"; STATUS_TEXT="Failure"; fi
          COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c1-7); REPO_NAME=$(echo "${{ github.repository }}" | sed 's/[._-]/\\&/g'); WORKFLOW_NAME=$(echo "${{ github.workflow }}" | sed 's/[._-]/\\&/g'); COMMIT_MESSAGE=$(echo "${{ github.event.head_commit.message }}" | sed 's/[._-]/\\&/g' | tr -d '\n\r');
          MESSAGE="*${STATUS_ICON} ${WORKFLOW_NAME}: ${STATUS_TEXT}*\n\n*Repository*: \`${REPO_NAME}\`\n*Commit*: \`${COMMIT_HASH}\` \- _${COMMIT_MESSAGE}_\n\n[View Workflow Run on GitHub](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})";
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" -d "text=${MESSAGE}" -d "parse_mode=MarkdownV2"