name: Build Ozone Docker Image
run-name: 'Build Ozone: ${{ github.event.head_commit.message || github.ref_name }}'

on:
  push:
    branches: [ main ]
    paths:
      - 'images/ozone/**'
      - '.github/workflows/build-ozone.yml'
      - '.github/workflows/reusable-docker-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'images/ozone/**'
      - '.github/workflows/build-ozone.yml'
      - '.github/workflows/reusable-docker-build.yml'
  workflow_dispatch:
    inputs:
      ozone_ref:
        description: 'Ozone repository ref (branch/tag/commit)'
        required: false
        default: 'release-1.4.0' # Ozone 1.4.0 is compatible with Hadoop 3
        type: string

env:
  # workflow_dispatch の入力、またはデフォルト値を設定
  OZONE_REF: ${{ github.event.inputs.ozone_ref || 'release-1.4.0' }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      ozone_version: ${{ steps.version.outputs.OZONE_VERSION }}
      ozone_tarball_name: ${{ steps.tarball_info.outputs.name }}
    steps:
      - name: Checkout Dockerfile repository
        uses: actions/checkout@v4

      - name: Extract Ozone version from ref
        id: version
        run: |
          # 'release-1.4.0' -> '1.4.0' のようにバージョン番号を抽出
          VERSION=$(echo "${{ env.OZONE_REF }}" | grep -o -E '[0-9]+\.[0-9]+\.[0-9]+')
          echo "OZONE_VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Checkout Apache Ozone repository
        uses: actions/checkout@v4
        with:
          repository: apache/ozone
          ref: ${{ env.OZONE_REF }}
          path: ozone-src

      - name: Install protoc compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-ozone-${{ env.OZONE_REF }}-${{ hashFiles('ozone-src/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-ozone-${{ env.OZONE_REF }}-

      - name: Build Ozone from source
        working-directory: ozone-src
        run: |
          mvn clean package -DskipTests -Pdist -Dmaven.javadoc.skip=true -B

      - name: Move tarball to Docker build context
        id: tarball_info
        run: |
          TARBALL_PATH=$(find ozone-src/hadoop-ozone/dist/target -name "ozone-*.tar.gz")
          TARBALL_NAME=$(basename ${TARBALL_PATH})
          mv ${TARBALL_PATH} images/ozone/
          echo "name=${TARBALL_NAME}" >> $GITHUB_OUTPUT

      - name: Upload build context artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-context
          path: images/ozone

  build:
    needs: prepare
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      workflow_name: 'Build Ozone Docker Image'
      image_name: 'terrestrials/ozone'
      image_context: 'images/ozone'
      image_version: ${{ needs.prepare.outputs.ozone_version }}
      build_args: OZONE_TARBALL=${{ needs.prepare.outputs.ozone_tarball_name }}
    secrets: inherit