name: Build Hadoop Docker Image
run-name: 'Build Hadoop: ${{ github.event.head_commit.message || github.ref_name }}'

on:
  push:
    branches: [ main ]
    paths:
      - 'images/hadoop/**'
      - '.github/workflows/build-hadoop.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'images/hadoop/**'
      - '.github/workflows/build-hadoop.yml'
  workflow_dispatch:
    inputs:
      hadoop_ref:
        description: 'Hadoop repository ref (branch/tag/commit)'
        required: false
        default: 'rel/release-3.4.1'
        type: string

env:
  HADOOP_VERSION: '3.4.1'

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Dockerfile repository
        uses: actions/checkout@v4

      - name: Checkout Apache Hadoop repository
        uses: actions/checkout@v4
        with:
          repository: apache/hadoop
          ref: ${{ github.event.inputs.hadoop_ref || 'rel/release-3.4.1' }}
          path: hadoop-src

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-hadoop-${{ github.event.inputs.hadoop_ref || 'rel/release-3.4.1' }}-${{ hashFiles('hadoop-src/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-hadoop-${{ github.event.inputs.hadoop_ref || 'rel/release-3.4.1' }}-

      - name: Build Hadoop from source
        working-directory: hadoop-src
        run: mvn clean package -Pdist -DskipTests -Dtar -Dmaven.javadoc.skip=true -B

      - name: Move tarball to Docker build context
        run: find hadoop-src/hadoop-dist/target -name "hadoop-*.tar.gz" -exec mv {} images/hadoop/ \;

      - name: Clean up to free disk space
        run: |
          echo "Before cleanup:"
          df -h
          
          rm -rf hadoop-src
          rm -rf ~/.m2/repository
          
          docker system prune -af
          
          echo "After cleanup:"
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: terrestrials
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate timestamp
        id: timestamp
        run: echo "timestamp=$(date -u +'%Y%m%d%H%M')" >> $GITHUB_OUTPUT

      - name: Extract metadata for Hadoop
        id: meta-hadoop
        uses: docker/metadata-action@v5
        with:
          images: terrestrials/hadoop
          tags: |
            type=raw,value=${{ env.HADOOP_VERSION }}-${{ steps.timestamp.outputs.timestamp }},enable={{is_default_branch}}
            type=raw,value=${{ env.HADOOP_VERSION }},enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Hadoop image
        uses: docker/build-push-action@v5
        with:
          context: images/hadoop
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-hadoop.outputs.tags }}
          labels: ${{ steps.meta-hadoop.outputs.labels }}
          build-args: |
            HADOOP_TARBALL=hadoop-*.tar.gz
            OZONE_TAG=latest
          platforms: linux/amd64,linux/arm64

      - name: Send notification to Telegram
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            STATUS_ICON="✅"
            STATUS_TEXT="Success"
          else
            STATUS_ICON="❌"
            STATUS_TEXT="Failure"
          fi
          COMMIT_HASH=$(echo "${{ github.sha }}" | cut -c1-7)
          REPO_NAME=$(echo "${{ github.repository }}" | sed 's/[._-]/\\&/g')
          WORKFLOW_NAME=$(echo "${{ github.workflow }}" | sed 's/[._-]/\\&/g')
          COMMIT_MESSAGE=$(echo "${{ github.event.head_commit.message }}" | sed 's/[._-]/\\&/g' | tr -d '\n\r')
          MESSAGE="*${STATUS_ICON} ${WORKFLOW_NAME}: ${STATUS_TEXT}*
          
          *Repository*: \`${REPO_NAME}\`
          *Commit*: \`${COMMIT_HASH}\` \- _${COMMIT_MESSAGE}_
          
          [View Workflow Run on GitHub](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=${MESSAGE}" \
          -d "parse_mode=MarkdownV2"
